# Generated by Django 5.1.5 on 2025-03-25 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osasapp.studentdb')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osasapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period_number', models.IntegerField()),
                ('is_present', models.BooleanField()),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osasapp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osasapp.studentdb')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osasapp.subject')),
            ],
        ),
    ]
