# Generated by Django 5.1.5 on 2025-03-27 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osasapp', '0002_attendance_attendancesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('class_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osasapp.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osasapp.facultydb')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osasapp.subject')),
            ],
        ),
    ]
